name: customer-demand-analysis-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - ipykernel=6.29.5
  - jinja2=3.1.4
  - matplotlib=3.9.1
  - numpy=2.0.1
  - pandas=2.2.2
  - python-dotenv=1.0.1
  - scipy=1.14.0
  - seaborn=0.13.2
